import { useState } from "react";
import { Copy, Sparkles, AlertTriangle, Loader2 } from "lucide-react";

export function ResponsibleFooter() {
  return (
    <p className="mt-3 text-[11px] text-muted-foreground/80 italic">
      Generated by Workly AI. Please verify critical information before sending.
    </p>
  );
}

export function CopyButton({ getText }: { getText: () => string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(getText());
          setCopied(true);
          setTimeout(() => setCopied(false), 1500);
        } catch {}
      }}
      className="inline-flex items-center gap-1.5 rounded-md border border-white/10 bg-white/5 px-2.5 py-1.5 text-xs text-foreground/80 hover:bg-white/10 transition"
    >
      <Copy className="size-3.5" /> {copied ? "Copied" : "Copy"}
    </button>
  );
}

export function EditableOutput({
  value,
  onChange,
  className = "",
  minRows = 8,
}: {
  value: string;
  onChange: (v: string) => void;
  className?: string;
  minRows?: number;
}) {
  return (
    <textarea
      value={value}
      onChange={(e) => onChange(e.target.value)}
      rows={minRows}
      className={`w-full resize-y rounded-lg input-surface p-4 text-sm text-foreground/95 outline-none focus:border-[#ff7a59]/60 focus:ring-2 focus:ring-[#ff7a59]/20 ${className}`}
    />
  );
}

export function OutputCard({
  title,
  loading,
  children,
}: {
  title: string;
  loading?: boolean;
  children: React.ReactNode;
}) {
  return (
    <div className="card-surface rounded-2xl p-5">
      <div className="mb-3 flex items-center justify-between">
        <div className="flex items-center gap-2 text-sm font-medium text-foreground/90">
          <Sparkles className="size-4 text-[#ff7a59]" /> {title}
        </div>
        {loading && <Loader2 className="size-4 animate-spin text-[#ff7a59]" />}
      </div>
      {children}
    </div>
  );
}

export function ErrorBanner({ message }: { message: string | null }) {
  if (!message) return null;
  return (
    <div className="mb-3 flex items-start gap-2 rounded-lg border border-red-500/20 bg-red-500/10 px-3 py-2 text-xs text-red-200">
      <AlertTriangle className="size-4 mt-0.5" /> <span>{message}</span>
    </div>
  );
}

export function ToolHeader({ title, subtitle }: { title: string; subtitle: string }) {
  return (
    <div className="mb-6">
      <h1 className="text-2xl font-semibold tracking-tight text-foreground">{title}</h1>
      <p className="mt-1 text-sm text-muted-foreground">{subtitle}</p>
    </div>
  );
}
